apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: openstack-ansibleee-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: OpenStackAnsibleEE is the Schema for the openstackansibleees API
      displayName: OpenStack Ansible EE
      kind: OpenStackAnsibleEE
      name: openstackansibleees.ansibleee.openstack.org
      version: v1alpha1
  description: The OpenStack Ansible Execution Environment Operator
  displayName: OpenStackAnsibleEE
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - ansible
  - execution
  links:
  - name: OpenStack Ansible EE Operator
    url: https://openstack-k8s-operators.github.io/openstack-ansibleee-operator
  maintainers:
  - email: jlarriba@redhat.com
    name: Juan Larriba
  maturity: alpha
  provider:
    name: jlarriba
  version: 0.0.0
