apiVersion: redhat.com/v1alpha1
kind: AnsibleEE
metadata:
  name: ansibleee-playbook
  namespace: openstack
spec:
  # We can specify either playbook, which will run with default ansible-runner options,
  # or args, which allows specify the whole command that we want to execute
  playbook: "deploy-tripleo-os-configure.yml"
  # args: ["ansible-runner", "run", "/runner", "-vvv", "-p", "test.yaml"]
  image: "quay.io/tripleomastercentos9/openstack-tripleo-ansible-ee:current-tripleo"
  inventory: |
    Compute:
      hosts:
        compute-0:
          ansible_host: 10.0.0.4
      vars:
        ansible_ssh_user: root
    allovercloud:
      children:
        Compute:
    overcloud:
      children:
        Compute:
  env:
    - name: ANSIBLE_FORCE_COLOR
      value: "True"
    - name: ANSIBLE_SSH_ARGS
      value: "-C -o ControlMaster=auto -o ControlPersist=80s"
    - name: ANSIBLE_ENABLE_TASK_DEBUGGER
      value: "True"
