apiVersion: redhat.com/v1alpha1
kind: AnsibleEE
metadata:
  name: ansibleee-extravolumes
  namespace: openstack
spec:
  playbook: "test.yaml"
  image: "quay.io/jlarriba/openstack-tripleo-ansible-ee:stable"
  inventory: |
          all:
            hosts:
              localhost
  extraMounts:
    - extraVolType: Ceph
      volumes:
      - name: ceph
        projected:
          sources:
          - secret:
              name: ceph-client-conf
          - secret:
              name: ceph-client-conf2
      mounts:
      - name: ceph
        mountPath: "/etc/ceph"
        readOnly: true
    - extraVolType: Ceph
      volumes:
      - name: ceph2
        projected:
          sources:
          - secret:
              name: ceph-client-conf
      mounts:
      - name: ceph2
        mountPath: "/etc/ceph2"
        readOnly: true
