apiVersion: redhat.com/v1alpha1
kind: AnsibleEE
metadata:
  name: ansibleee-test
  namespace: openstack
spec:
  playbook: "test.yaml"
  image: "quay.io/jlarriba/openstack-tripleo-ansible-ee:stable"
  inventory: |
          all:
            hosts:
              localhost
  extraMounts:
    - extraVolType: Ceph
      volumes:
      - name: ceph
        secret:
          secretName: ceph-client-conf
      mounts:
      - name: ceph
        mountPath: "/etc/ceph"
        readOnly: true

