apiVersion: v1
kind: Secret
metadata:
  name: ceph-client-conf2
  namespace: openstack
stringData:
  ceph.client.openstack2.keyring: |
    [client.openstack2]
        key = <magic key>
        caps mgr = "allow *"
        caps mon = "profile rbd"
        caps osd = "profile rbd pool=<pool>"
  ceph.conf: |
    [global]
    fsid = <fsid>
    mon_host = 1.2.3.4
