apiVersion: v1
kind: Secret
metadata:
  name: ceph-client-conf
  namespace: openstack
stringData:
  ceph.client.openstack.keyring: |
    [client.openstack]
        key = <magic key>
        caps mgr = "allow *"
        caps mon = "profile rbd"
        caps osd = "profile rbd pool=<Pools and profiles>
  ceph.conf: |
    [global]
    fsid = <magic fsid>
    mon_host = 1.2.3.4

