apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-configmap
  namespace: openstack
data:
  inventory.yaml: |
    Compute:
      hosts:
        compute-0:
          ansible_host: 10.0.0.4
      vars:
        ansible_ssh_user: root
    allovercloud:
      children:
        Compute:
    overcloud:
      children:
        Compute: